# Generated by Django 6.0 on 2025-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='1-5 rating', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
