# Generated by Django 6.0 on 2025-12-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_completed_at_ride_feedback_ride_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='platform_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='rider_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
