# Generated by Django 6.0 on 2025-12-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_platform_profit_ride_rider_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverlocation',
            options={'verbose_name': 'Driver Location', 'verbose_name_plural': 'Driver Locations'},
        ),
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ride',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 rating', null=True),
        ),
    ]
