# Generated by Django 6.0 on 2025-12-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_driverlocation_options_alter_ride_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('total_seats', models.PositiveIntegerField(default=4)),
                ('available_seats', models.PositiveIntegerField(default=4)),
                ('fare_per_seat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
