# Generated by Django 6.0 on 2025-12-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_delivery_charge', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('rider_commission_percentage', models.PositiveIntegerField(default=80, help_text='Percentage of delivery fee given to rider')),
            ],
        ),
    ]
