# Generated by Django 6.0 on 2025-12-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='default_delivery_charge',
            new_name='food_delivery_charge',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='rider_commission_percentage',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='food_commission_percentage',
            field=models.PositiveIntegerField(default=80, help_text='Food: % of delivery fee for rider'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='mall_commission_percentage',
            field=models.PositiveIntegerField(default=10, help_text='Mall: % of order total for platform (rest to shop)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='parcel_commission_percentage',
            field=models.PositiveIntegerField(default=80, help_text='Parcels: % of price for rider'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='ride_commission_percentage',
            field=models.PositiveIntegerField(default=80, help_text='Rides: % of fare for driver'),
        ),
    ]
