# Generated by Django 6.0 on 2025-12-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, help_text='URL to an image of the restaurant', max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
            ],
        ),
    ]
