# Generated by Django 6.0 on 2025-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parcelrequest',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
