# Generated by Django 6.0 on 2025-12-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_riderprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant', 'Restaurant'), ('admin', 'Admin'), ('rider', 'Rider'), ('seller', 'Seller')], default='customer', max_length=20),
        ),
    ]
