# Generated by Django 6.0 on 2025-12-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='rider_type',
            field=models.CharField(choices=[('food', 'Food Delivery'), ('parcel', 'Parcel Delivery'), ('both', 'Food & Parcel Delivery')], default='food', help_text='Type of delivery service this rider provides', max_length=20),
        ),
    ]
