# Generated by Django 6.0 on 2025-12-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_riderprofile_rider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='rider_type',
            field=models.CharField(choices=[('food', 'Food Delivery'), ('parcel', 'Parcel Delivery'), ('both', 'Food & Parcel Delivery')], default='food', max_length=20),
        ),
    ]
