# Generated by Django 6.0 on 2025-12-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_riderprofile_rider_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='rider_type',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='is_food_rider',
            field=models.BooleanField(default=False, verbose_name='Food Delivery'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='is_parcel_rider',
            field=models.BooleanField(default=False, verbose_name='Parcel Delivery'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='is_ride_rider',
            field=models.BooleanField(default=False, verbose_name='Ride Sharing'),
        ),
    ]
